### ISSUE TITLE
The skill prompts users for an input then immediately closes the session.

### ISSUE THREAD

**Issue by baynado** [alexa/skill-sample-nodejs-berry-bash#1]
"_The skill prompts users for an input then immediately closes the session. Make sure the session remains open anytime users are prompted for inputs.

Please see test case 4.1 from our Submission Checklist for guidance on session management._"

That was the feedback by your skill certification team!!! I've just translated the text from english into german.

**Comment by franklin-lobb** [comment]
@baynado are you still facing this issue?

**Comment by baynado** [comment]
No, i have a solution found.

Von meinen Samsung S8 gesendet.

franklin-lobb <notifications@github.com> schrieb am Mi., 30. Mai 2018,
18:41:
